spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_prod_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
message: auth service prod      
